fermate = {
    "Piazza di Povo": "Povo Piazza Manci",
    "Povo vicino alla chiesa": "Povo Piazza Manci",
    "povo poste": "Povo Piazza Manci",
    "Povo piazza centrale": "Povo Piazza Manci",
    "Povo casa riposo": "Povo Casa di Riposo",
    "povo casa di riposo": "Povo Casa di Riposo",
    "Stazione Trento": "Piazza Dante Stazione Fs",
    "Piazza Dante": "Piazza Dante Stazione Fs",
    "centrale trento": "Piazza Dante Stazione Fs",
    "Staz trento": "Piazza Dante Stazione Fs",
    "Ingegneria informatica Povo": "Povo Polo Scientifico Ovest",
    "FBK Povo": "Povo Polo Scientifico Ovest",
    "Fondazione Bruno Kessler Povo": "Povo Polo Scientifico Ovest",
    "Ingegneria civile Mesiano": "Mesiano Fac. Ingegneria",
    "Ingegneria ambientale Mesiano": "Mesiano Fac. Ingegneria",
    "Ingegneria meccanica Mesiano": "Mesiano Fac. Ingegneria",
    "Fermta Buonconsiglio": "Castello Buonconsiglio",
    "itea Centochiavi": "Guardini Centochiavi",
    "top center": "Zambra Top Center",
    "Top Center": "Zambra Top Center",
    "ist. d'arte": "Zambra Ist. D'arte Vittoria",
    "istituto d'arte": "Zambra Ist. D'arte Vittoria",
    "Bunaga sopramonte": "Sopramonte Bunaga",
    "3 cime sopramonte": "Sopramonte Bunaga",
    "maso Petoci": "Sopramonte M.Petoci",
    "centrale sopramonte": "Sopramonte Piazza Oveno",
    "conad sopramonte": "Sopramonte Piazza Oveno",
    "piazza sopramonte": "Sopramonte Piazza Oveno",
    "bivio sopramonte": "Sopramonte Bivio Baselga",
    "cappella Campra": "Sopramonte Campra",
    "cappella Sopramonte": "Sopramonte Campra",
    "macelleria Segata": "Sp 85 Soraval",
    "segheria Sopramonte": "Sopramonte Valle",
    "Baselga bondone": "Baselga Del Bondone",
    "centrale Baselga": "Baselga Del Bondone",
    "centrale Cadine": "Cadine Strada Gardesana",
    "tornante Cadine": "Cadine Della Fornas",
    "bus de vela": "Forte Bus De Vela",
    "Cavalcavia Stazione Trento": "Cavalcavia S.Lorenzo",
    "Cavalcavia stazione": "Cavalcavia S.Lorenzo",
    "Piazza dante dietro Regione": "Gazzoletti Piazza Dante",
    "piazza dante dietro palazzo regione": "Gazzoletti Piazza Dante ",
    "porta nuova": "S.Francesco Porta Nuova",
    "Scuola Pozzo": "Barbacovi Itg Pozzo",
    "superiori geometri pozzo": "Barbacovi Itg Pozzo",
    "Pozzo": "Barbacovi Itg Pozzo",
    "torrente fersina piazza vicenza": "Piazza Vicenza",
    "fersina piazza Vicenza": "Piazza Vicenza",
    "inizio via Gorizia": "Gorizia Adamello",
    "ospedale Bolghera": "Bolghera S.Antonio",
    "poli Bolghera": "Bolghera S.Antonio",
    "farmacia Bolghera": "Bolghera S.Antonio",
    "chiesa Antonio Bolghera": "Bolghera S.Antonio",
    "Chiesa Mario Borzaga Bolghera": "Bolghera S.Antonio"
}

