sinonimi = {
    "Piazza Manci di Povo": "Povo Piazza Manci",
    "Povo piazza manci vicino alla chiesa": "Povo Piazza Manci",
    "Povo piazza manci centrale": "Povo Piazza Manci",
    "FBK Povo Polo": "Povo Polo Scientifico Ovest",
    "3 cime sopramonte bunaga": "Sopramonte Bunaga",
    "cappella Campra Sopramonte": "Sopramonte Campra",
    "inizio via Gorizia adamello": "Gorizia Adamello",
    "Pozzo Itg": "Barbacovi Itg Pozzo",
    "Piazza dante gazzoletti": "Gazzoletti Piazza Dante",
    "Cavalcavia Stazione Trento": "Cavalcavia S.Lorenzo",
    "conad sopramonte oveno": "Sopramonte Piazza Oveno",
    "Trento": "Trento FS",
    "Povo": "Povo Piazza Manci",
    "Mesiano": "Mesiano Stazione Fs",
    "Cognola": "Cognola Chiesa",
    "Martignano": "Martignano Chiesa",
    "Sopramonte": "Sopramonte Piazza Oveno",
    "Cadine": "Cadine Voltei",
    "Ravina": "Ravina Chiesa",
    "Stazione Trento": "Piazza Dante Stazione Fs",
    "stazione trento": "Piazza Dante Stazione Fs",
    "trento stazione": "Piazza Dante Stazione Fs",
    "Trento stazione FS": "Piazza Dante Stazione Fs",
    "Trento Stazione": "Piazza Dante Stazione Fs",
    "Caldonazzo": "Caldonazzo FS",
    "caldonazzo": "Caldonazzo FS",
    "Calceranica": "Calceranica FS",
    "calceranica": "Calceranica FS",
    "san cristoforo": "S.Cristoforo al Lago FS",
    "San Cristoforo": "S.Cristoforo al Lago FS",
    "Roncegno": "Roncegno B.M FS",
    "roncegno": "Roncegno B.M FS",
    "Levico": "Levico Terme FS",
    "levico": "Levico Terme FS",
    "Pergine": "Pergine Valsugana FS",
    "pergine": "Pergine Valsugana FS",
    "borgo valsugana": "Borgo Valsugana Centro FS",
    "borgo vecchia": "Borgo Valsugana Centro FS",
    "borgo centrale": "Borgo Valsugana Centro FS",
    "borgo centro commerciale": "Borgo Valsugana Est FS",
    "borgo est": "Borgo Valsugana Est FS",
    "borgo": "Borgo Valsugana Centro FS",
    "bassano": "Bassano del Grappa FS",
    "Bassano": "Bassano del Grappa FS",
    "Bassano del grappa": "Bassano del Grappa FS",
    "bassano del grappa": "Bassano del Grappa FS",
    "Villazzano Stazione": "Villazzano Stazione FS",
    "Piazza Dante Stazione": "Piazza Dante Stazione FS",
    "Mesiano Stazione": "Mesiano Stazione FS",
    "Bolzano": "Bolzano FS",
    "Laives": "Laives FS",
    "Bronzolo": "Bronzolo FS",
    "Ora-Auer": "Ora-Auer FS",
    "Ora": "Ora-Auer FS",
    "Egna": "Egna-Termeno FS",
    "Egna": "Egna-Termeno FS",
    "Termeno": "Egna-Termeno FS",
    "Magrè": "Magre'-Cortaccia FS",
    "Cortaccia": "Magre'-Cortaccia FS",
    "Salorno": "Salorno FS",
    "Mezzocorona": "Mezzocorona FS",
    "Lavis": "Lavis FS",
    "Mori": "Mori FS",
    "Rovereto": "Rovereto FS",
    "Serravalle": "Serravalle FS",
    "Ala": "Ala FS",
    "Avio": "Avio FS",
    "Borghetto": "Borghetto FS",
    "Peri": "Peri FS",
    "Dolce'": "Dolce' FS",
    "Verona": "VeronaPN",
    "Solagna": "Solagna FS",
    "S.Nazario": "S.Nazario FS",
    "Carpane' Valstagna": "Carpane' Valstagna FS",
    "S.Marino": "S.Marino FS",
    "Cismon del Grappa": "Cismon del Grappa FS",
    "Primolano": "Primolano FS",
    "Tezze di Grigno": "Tezze di Grigno FS",
    "Grigno": "Grigno FS",
    "Strigno": "Strigno FS",
    "San bartolomeo": "S.Bartolameo FS",
    "Malè": "Male Ferrovia",
    "Malé": "Male Ferrovia",
    "Male'": "Male Ferrovia",
    "Male": "Male Ferrovia",
    "Sanseverino": "Sanseverino Albere/Muse",
    "Gardolo": "Gardolo Ferrovia",
    "Spini": "Spini Zona Industriale Ferrovia",
    "Spini di Gardolo": "Spini Zona Industriale Ferrovia",
    "Lamar": "Lamar Ferrovia",
    "Lavis": "Lavis Staz.Ftm",
    "Zambana": "Zambana Ferrovia",
    "Nave San Felice": "Nave S.Felice Ferrovia",
    "Nave": "Nave S.Felice Ferrovia",
    "Grumo": "Grumo S.Michele Ferrovia",
    "Grumo San Michele": "Grumo S.Michele Ferrovia",
    "San Michele": "Grumo S.Michele Ferrovia",
    "Grum s. michele": "Grumo S.Michele Ferrovia",
    "Mezzocorona": "Mezzocorona Ferrovia",
    "Mezzocorona Borgata": "Mezzocorona Borgata Ferrovia",
    "Mezzolombardo": "Mezzolombardo Ferrovia",
    "Crescino": "Crescino Ferrovia",
    "Mollaro": "Mollaro Ferrovia",
    "Segno": "Segno Ferrovia",
    "Taio": "Taio Ferrovia",
    "Dermulo": "Dermulo Ferrovia",
    "Tassullo": "Tassullo Ferrovia",
    "Cles Mascotti": "Cles Negozio Mascotti",
    "Cles Polo": "Cles Polo Scolastico Ferrovia",
    "Cles": "Cles Ferrovia",
    "Mostizzolo": "Mostizzolo Ferrovia",
    "Bozzana": "Bozzana Ferrovia",
    "Tozzaga": "Tozzaga Ferrovia",
    "Cassana": "Cassana Ferrovia",
    "Cavizzana": "Cavizzana Ferrovia",
    "Caldes": "Caldes Ferrovia",
    "Terzolas": "Terzolas Ferrovia",
    "Croviana": "Croviana Ferrovia",
    "Monclassico": "Monclassico Ferrovia",
    "Dimaro": "Dimaro Ferrovia",
    "Mastellina": "Mastellina Ferrovia",
    "Daolasa": "Daolasa Ferrovia",
    "Piano": "Piano Ferrovia",
    "Marilleva": "Marilleva Ferrovia",
    "Mezzana": "Mezzana Ferrovia"    
}